# 建立一个名为CI的工作流
name: CI

# 监听 master上的push事件
on:
  push:
  branches: [ master ]

# 开始任务
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Build
    run: npm install && npm run build
   - name: Deploy
    uses: cross-the-world/scp-pipeline@master
    env:
     WELCOME: "ssh scp ssh pipelines"
     LASTSSH: "Doing something after copying"
    with:
     host: ${{ secrets.TG_HOST }}
     user: ${{ secrets.TG_USER }}
     pass: ${{ secrets.TG_PASS }}
     connect_timeout: 10s
     local: './dist/*'
     remote: /www/wwwroot/qiushui/fronted_end/dist/
